<a href="https://colab.research.google.com/github/erikromerovelasco-dev/pandas-/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv("ModalidadVirtual.csv")
df

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí
3,3,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No
4,4,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Hombre,Sí
...,...,...,...,...,...,...,...,...,...
217,230,2020-12-10,Gestión Turística y Hotelera,Si,Horario flexible.,Conexión a internet.,19,Mujer,Sí
218,231,2020-12-11,Ingeniería de Sistemas,No,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",23,Mujer,No
219,232,2020-12-11,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí
220,233,2020-12-11,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí
221,234,2020-12-12,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí

In [ ]:
df.head(5)

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí
3,3,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No
4,4,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Hombre,Sí

In [ ]:
df.describe()

       Unnamed: 0        edad
count  222.000000  222.000000
mean   119.896396   28.166667
std     67.424522    7.556374
min      0.000000   17.000000
25%     63.250000   22.000000
50%    121.500000   27.000000
75%    177.750000   33.000000
max    234.000000   54.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222 entries, 0 to 221
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  222 non-null    int64
 1   time        222 non-null    object
 2   carrera     222 non-null    object
 3   acepta      222 non-null    object
 4   positivo    222 non-null    object
 5   negativo    222 non-null    object
 6   edad        222 non-null    int64
 7   sexo        222 non-null    object
 8   trabajo     222 non-null    object
dtypes: int64(2), object(7)
memory usage: 15.7+ KB

In [ ]:
df.isnull().sum()

Unnamed: 0    0
time          0
carrera       0
acepta        0
positivo      0
negativo      0
edad          0
sexo          0
trabajo       0
dtype: int64

In [ ]:
df.fillna(0)

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí
3,3,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No
4,4,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Hombre,Sí
...,...,...,...,...,...,...,...,...,...
217,230,2020-12-10,Gestión Turística y Hotelera,Si,Horario flexible.,Conexión a internet.,19,Mujer,Sí
218,231,2020-12-11,Ingeniería de Sistemas,No,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",23,Mujer,No
219,232,2020-12-11,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí
220,233,2020-12-11,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí
221,234,2020-12-12,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí

In [ ]:
df_filtrado=df[df["edad"]>=18]
df_filtrado

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí
3,3,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No
4,4,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Hombre,Sí
...,...,...,...,...,...,...,...,...,...
217,230,2020-12-10,Gestión Turística y Hotelera,Si,Horario flexible.,Conexión a internet.,19,Mujer,Sí
218,231,2020-12-11,Ingeniería de Sistemas,No,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",23,Mujer,No
219,232,2020-12-11,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí
220,233,2020-12-11,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí
221,234,2020-12-12,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí

In [ ]:
#df.dropna()

In [ ]:
df_filtrado=df[(df["edad"]>=18)&(df["edad"]<40)]
df_filtrado

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí
3,3,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No
4,4,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Hombre,Sí
...,...,...,...,...,...,...,...,...,...
217,230,2020-12-10,Gestión Turística y Hotelera,Si,Horario flexible.,Conexión a internet.,19,Mujer,Sí
218,231,2020-12-11,Ingeniería de Sistemas,No,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",23,Mujer,No
219,232,2020-12-11,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí
220,233,2020-12-11,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí
221,234,2020-12-12,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí

In [ ]:
df=df[["edad","sexo"]]
df

     edad    sexo
0      20  Hombre
1      26  Hombre
2      20   Mujer
3      18   Mujer
4      39  Hombre
..    ...     ...
217    19   Mujer
218    23   Mujer
219    25  Hombre
220    20   Mujer
221    23  Hombre

[222 rows x 2 columns]

In [ ]:
df["edad"].sum()

np.int64(6253)

In [ ]:
df["edad"].mean()

np.float64(28.166666666666668)

In [ ]:
df["edad"].std()

7.556374353054468

In [ ]:
print(df.groupby("sexo")["edad"].mean())

sexo
Hombre    28.816667
Mujer     27.401961
Name: edad, dtype: float64

In [ ]:
tabla_piv=pd.pivot_table(df,values="edad",index="sexo",aggfunc="mean")
tabla_piv

             edad
sexo
Hombre  28.816667
Mujer   27.401961

In [ ]:
df_ordenado=df.sort_values(by="edad",ascending=True)
df_ordenado

     edad    sexo
98     17  Hombre
86     17   Mujer
75     17   Mujer
74     17   Mujer
3      18   Mujer
..    ...     ...
25     46  Hombre
141    47   Mujer
85     49  Hombre
64     50  Hombre
114    54   Mujer

[222 rows x 2 columns]

In [ ]:
df_ordenado.to_csv("ModalidadVirtual_modificado.xslx", index=False)